[formatter.mdformat]
command = "mdformat"
options = []
excludes = []
includes = ["*.md"]

[formatter.deadnix]
command = "deadnix"
options = ["--edit"]
excludes = []
includes = ["*.nix"]

[formatter.nixfmt-rfc-style]
command = "nixfmt"
options = []
excludes = []
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
excludes = []
includes = ["*.cjs","*.css","*.html","*.js","*.jsx","*.mdx","*.mjs","*.scss","*.ts","*.tsx","*.vue"]

[formatter.yamlfmt]
command = "yamlfmt"
options = []
excludes = []
includes = ["*.yml","*.yaml"]

[formatter.jsonfmt]
command = "jsonfmt"
options = ["-w"]
excludes = []
includes = ["*.json","*.jsonc"]

[global]
excludes = ["*.png","*.jpg","*.jpeg", "LICENSE"]
